---
name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
      - uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "5.0"
      - uses: browser-actions/setup-geckodriver@latest
        with:
          geckodriver-version: "0.32.2"
      - uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: "111.0.1"
      - run: bundle install
      - uses: coactions/setup-xvfb@v1
        with:
          run: bundle exec rake
